### ISSUE TITLE
请问模板语法能换成vue默认的嘛？

### ISSUE THREAD

**Issue by Chinalink** [lfyfly/vue-waterfall-easy#12]
Module build failed: ReferenceError: Unknown plugin "transform-vue-jsx" specified in "E:\\Testing\\mp-kite\\node_modules\\vue-waterfall-easy\\.babelrc" at 0, attempted to resolve relative to "E:\\Testing\\mp-kite\\node_modules\\vue-waterfall-easy"
    at E:\Testing\mp-kite\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (E:\Testing\mp-kite\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (E:\Testing\mp-kite\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (E:\Testing\mp-kite\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\Testing\mp-kite\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\Testing\mp-kite\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\Testing\mp-kite\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\Testing\mp-kite\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\Testing\mp-kite\node_modules\babel-loader\lib\index.js:173:20)

 @ ./~/vue-waterfall-easy/src/vue-waterfall-easy/vue-waterfall-easy.vue 8:0-123
 @ ./~/babel-loader/lib!./~/mpvue-loader/lib/selector.js?type=script&index=0!./src/pages/find-list/find-list.vue
 @ ./src/pages/find-list/find-list.vue
 @ ./src/pages/find-list/main.js

由于该组件使用了jsx语法，导致运行出错

**Comment by lfyfly** [comment]
你把pug复制进去转换一下
https://pug.bootcss.com/language/code.html
