### ISSUE TITLE
import plugin error

### ISSUE THREAD

**Issue by RosApr** [lfyfly/vue-waterfall-easy#14]
hi
thansk for your plugin but when i use this, it's occur an error in 
#error (compile error)
in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-waterfall-easy/src/vue-waterfall-easy/vue-waterfall-easy.vue
Module build failed: ReferenceError: Unknown plugin "transform-vue-jsx" specified in "my file path"
node_modules/vue-waterfall-easy/.babelrc" at 0, attempted to resolve relative to "/node_modules/vue-waterfall-easy"
    at /node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (//node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init /node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (//node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/node_modules/babel-loader/lib/index.js:49:20)

waiting your apply thanks

**Comment by lfyfly** [comment]
npm install --save-dev babel-plugin-transform-react-jsx

**Comment by lfyfly** [comment]
npm install --save-dev babel-plugin-transform-vue-jsx

**Comment by RosApr** [comment]
you main install this plugin in my project?

**Comment by lfyfly** [comment]
yes

**Comment by RosApr** [comment]
my project is base on vue-cli which webpack version is 2.x.x

**Comment by RosApr** [comment]
这能私信么。。。我英语说的费劲..

**Comment by lfyfly** [comment]
你咋不早用中文呢？还以为你是外国友人呢

**Comment by RosApr** [comment]
哎呀。。。

**Comment by lfyfly** [comment]
你加我qq 410793635

**Comment by RosApr** [comment]
哎呀
我是vue-cli的项目
引进来之后就报错了。。就是上班的
我看webpack 版本是2.x 但是看样子需要3.x哦？
怎么搞
我把你说的plugin下载了但还是有问题啊

**Comment by lfyfly** [comment]
那就升级下vue-cli

**Comment by RosApr** [comment]
这个怕是大工程吧。。。

**Comment by RosApr** [comment]
加你了
同意下
